### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by FergM** [MarcosCarreira/StatisticalConsequencesOfFatTails#2]
@MarcosCarreira 

# What
* I guess MIT or BSD license
* Django has a brief comment on the matter [here](https://docs.djangoproject.com/en/3.1/intro/reusable-apps/)

# Why
* So others can use the code
* and know what the expectations are

**Comment by MarcosCarreira** [comment]
@FergM  , I'm not that knowledgeable on this, I'm Ok with you taking this lead.
